services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8100:80"
    depends_on:
      - php
    networks:
      - tasklinker_network

  php:
    build: .
    volumes:
      - .:/var/www
    depends_on:
      - database
    networks:
      - tasklinker_network

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-task_linker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-plout}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - tasklinker_network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###
  adminer:
    image: adminer:latest
    volumes:
      - ./adminer-themes:/var/www/html/designs
    environment:
      ADMINER_DESIGN: "lucas-sandery"
    restart: always
    depends_on:
      - database
    ports:
      - "8082:8080"
    networks:
      - tasklinker_network

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  tasklinker_network:
    driver: bridge
