
services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - tasklinker_network
      ###< symfony/mailer ###


  messenger-worker:
    image: php:8.2-cli
    volumes:
      - .:/app
    working_dir: /app
    command: php bin/console messenger:consume async --time-limit=3600
    depends_on:
      - mailer
    restart: unless-stopped
